# Generated by Django 5.2.1 on 2025-12-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_catergory_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productnew',
            name='image_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
